# Alacritty config for Windows (WSL)
# Place at %APPDATA%\alacritty\alacritty.toml
# Set default WSL distro: wsl --set-default Ubuntu
# If you need to use a specific distro, run: wsl --set-default <distro-name>

[general]
import = ["common.toml", "alacritty-theme/themes/omni.toml"]
# import = ["common.toml", "alacritty-theme/themes/pastel_dark.toml"]
# import = ["common.toml", "alacritty-theme/themes/pencil_dark.toml"]

[terminal.shell]
program = "wsl"
args = [
  "--cd",
  "~",
  # "-e",
  # "zsh -l -c \"source .zshrc && tmux new-session -A -s main\"",
]


[font]
size = 10
builtin_box_drawing = true

[font.offset]
x = 1
y = 5

[font.normal]
family = "M+1Code Nerd Font"
style = "Medium"

[font.bold]
family = "M+1Code Nerd Font"
style = "Bold"

[font.italic]
family = "M+1Code Nerd Font"
style = "Italic"

[font.bold_italic]
family = "M+1Code Nerd Font"
style = "Bold Italic"

# Ensure proper DPI awareness
[window]
dynamic_title = true
