# This file should be placed at %APPDATA%\alacritty\alacritty.toml on Windows
# To create the symlink, run as administrator: powershell -File link-alacritty.ps1
[terminal.shell]
program = "C:\\Windows\\System32\\wsl.exe"
args = ["-d", "Ubuntu-24.04", "--cd", "~", "-e", "zsh -l -c \"source .zshrc && tmux\""]

[font]
size = 10.0

[font.offset]
x = 1
y = 5

[window]
padding = { x = 10, y = 10 }

[font.normal]
family = "M+1Code Nerd Font Mono"

[font.bold]
family = "M+1Code Nerd Font Mono"
style = "Bold"

[font.italic]
family = "M+1Code Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "M+1Code Nerd Font Mono"
style = "Bold Italic"

[keyboard]
bindings = [
  { key = "Backspace", mods = "Control", chars = "\u0017" }
]